import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import FadeIn from '../components/FadeIn';
import PageHero from '../components/PageHero';
import Seo from '../components/Seo';
import { fetchArticles, fetchNewsletterPosts } from '../lib/api';

// The club is supplying its own articles (Oct 2026). Until they are published
// in the admin console, the page shows an honest empty state.
const CURATED_ARTICLES = [];

const CATEGORIES = [
  'All Topics',
  'Market Updates',
  'Financial Literacy',
  'Student Finance',
  'Investment Strategies',
  'Crypto & Digital Assets',
  'Forex & Trading',
];

// Real, downloadable files generated by the club (see scripts/generate-resources.cjs)

export default function Blog() {
  const [category, setCategory] = useState('All Topics');
  const [query, setQuery] = useState('');
  const [dbArticles, setDbArticles] = useState([]);
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    let alive = true;
    fetchArticles().then((rows) => {
      if (alive && rows.length) setDbArticles(rows);
    });
    fetchNewsletterPosts().then((rows) => {
      if (alive && rows.length) setPosts(rows);
    });
    return () => {
      alive = false;
    };
  }, []);

  const articles = dbArticles.length ? dbArticles : CURATED_ARTICLES;


  // Merge admin-created articles (club-written or curated additions) with the
  // verified seed library. Normalize DB rows (source_url/source_name) and the
  // curated seed (url/publication). Club articles (body, is_external:false)
  // are deduped from the seed list so they never appear twice.
  const seed = CURATED_ARTICLES.filter(
    (s) => !dbArticles.some((d) => d.title === s.title),
  );
  const all = [...dbArticles, ...seed];
  const normalized = all.map((a) => ({
    ...a,
    url: a.url || a.source_url,
    publication: a.publication || a.source_name,
  }));

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return normalized.filter((a) => {
      const matchesCategory = category === 'All Topics' || (a.category || '') === category;
      const matchesQuery =
        !q ||
        a.title.toLowerCase().includes(q) ||
        (a.summary || '').toLowerCase().includes(q) ||
        (a.publication || '').toLowerCase().includes(q) ||
        (a.author || '').toLowerCase().includes(q);
      return matchesCategory && matchesQuery;
    });
  }, [category, query, normalized]);

  return (
    <>
      <Seo
        title="Blog"
        description="Articles on Nigerian markets, investing and student finance from the Babcock Investors Club."
      />
      <PageHero
        crumb="Blog"
        title="Reading from the club."
        description="Articles on Nigerian markets, investing and student finance, chosen by BIC members."
      />

      {normalized.length === 0 ? (
      <section className="section container">
        <div className="offline-notice">
          <h3>The first articles are on the way.</h3>
          <p>The club is putting together its reading list. Check back soon, or follow us on Instagram for updates.</p>
        </div>
      </section>
      ) : (
      <FadeIn className="section container">
        <div className="blog-header">
          <h2 className="section-title" style={{ marginBottom: 0 }}>
            Articles
          </h2>
          <div className="blog-search">
            <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
            <input
              type="text"
              placeholder="Search articles, topics, sources..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
          </div>
        </div>

        <div className="blog-categories">
          {CATEGORIES.map((c) => (
            <button
              type="button"
              key={c}
              className={`category-btn${category === c ? ' active' : ''}`}
              onClick={() => setCategory(c)}
            >
              {c}
            </button>
          ))}
        </div>

        {filtered.length === 0 ? (
          <div className="text-center" style={{ padding: '60px 0', color: '#55617e' }}>
            No articles match your search. Try a different keyword or category.
          </div>
        ) : (
          <div className="blog-grid">
            {filtered.map((a) => {
              const isClub = !!(a.body && a.is_external === false);
              const Inner = (
                <>
                  <div className="blog-img">
                    <span className="blog-badge">{isClub ? 'Club Article' : a.category || 'Articles'}</span>
                    {a.cover_url ? (
                      <img src={a.cover_url} alt={a.title} loading="lazy" />
                    ) : (
                      <div className="blog-img-placeholder">BIC</div>
                    )}
                  </div>
                  <div className="blog-content">
                    <div className="blog-meta">
                      <span>{a.published_date || 'Latest'}</span>
                      {isClub ? <span>by BIC Editorial Team</span> : <span>via {a.publication}</span>}
                    </div>
                    <h3 className="blog-title">{a.title}</h3>
                    <p className="blog-desc">{a.summary}</p>
                    <div className="blog-author">
                      <div className="author-info">
                        <h4>{isClub ? 'Babcock Investors Club' : a.author || a.source_name}</h4>
                        <p style={{ color: 'var(--sky-blue-dark)', fontWeight: 600 }}>
                          {isClub ? 'Read on the blog →' : 'Read the full article →'}
                        </p>
                      </div>
                    </div>
                  </div>
                </>
              );
              return (
                <div className="blog-card" key={a.title || a.id}>
                  {isClub ? (
                    <Link to={`/blog/${a.id}`} className="blog-card-link">{Inner}</Link>
                  ) : (
                    <a href={a.url} target="_blank" rel="noreferrer" className="blog-card-link">{Inner}</a>
                  )}
                </div>
              );
            })}
          </div>
        )}

        <p className="text-center" style={{ color: '#55617e', fontSize: '0.85rem', marginTop: 32 }}>
          Articles are shared for educational purposes. Linked content belongs to the original publications and authors.
        </p>
      </FadeIn>
      )}

      {/* NEWSLETTER POSTS (published by admins) */}
      {posts.length > 0 && (
        <FadeIn className="section container">
          <div className="text-center" style={{ marginBottom: 48 }}>
            <h2 className="section-title">
              Club Newsletters
            </h2>
            <div className="gold-line"></div>
            <p className="section-subtitle">Official announcements and market updates from the BIC executive team.</p>
          </div>
          <div className="newsletter-list">
            {posts.map((p) => (
              <article className="newsletter-post" key={p.id}>
                <div className="newsletter-head">
                  <h3>{p.subject}</h3>
                  <span>{new Date(p.created_at).toLocaleDateString()}</span>
                </div>
                <p style={{ whiteSpace: 'pre-line' }}>{p.body}</p>
              </article>
            ))}
          </div>
        </FadeIn>
      )}

    </>
  );
}
